### ISSUE TITLE
✅ Issue: CI/CD & Deployment Altyapısının Kurulması

### ISSUE THREAD

**Issue by developersailor** [developersailor/turdes-backend#37]
Alan: deployment, devops, railway, docker

⸻

🎯 Amaç

Turdes backend API’sini güvenli, otomatik ve sürekli entegre/deploy edilebilir hale getirmek. Railway veya alternatif servisler (Render, Fly.io, Heroku) üzerinden production ortamda yayına almak. Docker desteğiyle local/test ortamlarında taşınabilirlik sağlamak.

⸻

📌 Yapılacaklar

1. Dockerfile Oluştur
	•	NestJS için optimize Dockerfile yaz:

```
FROM node:18-alpine
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build
CMD ["node", "dist/main"]
```

	•	.dockerignore dosyası ekle: node_modules, dist, .env, vs.

2. Docker Compose (Opsiyonel)
	•	PostgreSQL + API birlikte çalışsın:

```
version: '3'
services:
  api:
    build: .
    ports:
      - "3000:3000"
    env_file: .env
    depends_on:
      - db
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: ...
      POSTGRES_PASSWORD: ...
      POSTGRES_DB: ...
```

3. Railway Deployment
	•	Railway projesi oluştur
	•	DATABASE_URL, JWT_SECRET, FIREBASE_... gibi env değişkenlerini Railway dashboard’a tanımla
	•	prisma migrate deploy komutu start öncesinde çalıştırılmalı
	•	npm run build && npm run start:prod komutu Railway’de çalışmalı

4. CI/CD Pipeline (GitHub Actions Örneği)
	•	.github/workflows/deploy.yml:

```
name: Deploy API

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: npm install
      - run: npm run build
      - run: npm run test
      - name: Deploy to Railway
        run: curl -X POST ${{ secrets.RAILWAY_DEPLOY_HOOK }}
```

⸻

🔗 Entegrasyonlar

- [ ] 	•	test modülü ile CI üzerinde test geçmeden deploy’a izin verilmemeli
- [ ] 	•	prisma migrate deploy entegrasyonu mutlaka tanımlanmalı

⸻

🧪 Test Planı

- [ ] 	•	Local Docker üzerinde API ayağa kalkıyor mu?
- [ ] 	•	CI pipeline her push’ta testleri çalıştırıyor mu?
- [ ] 	•	Railway üzerinde production ayağa kalkıp /api erişilebiliyor mu?
